### ISSUE TITLE
Installed PWA shown as external

### ISSUE THREAD

**Issue by sunetraalex** [lmssiehdev/calmwhisper#6]
Hey, I just installed the app but on my device it shows as a external page.

I checked the `manifest.json` and it seems ok though.

Here's how it looks like on my phone.

![Screenshot_2023-02-10-18-06-20-973_com android chrome](https://user-images.githubusercontent.com/17137223/218153197-430aa7bf-70a1-4b81-a2f8-4ec9a3b435c5.jpg)

**Comment by lmssiehdev** [comment]
Hi, thank you for reporting the issue. I've made a pull request to resolve it. Could you please confirm if the issue has been fixed on the development build https://yume-dosw1crq9-lmssiehdev.vercel.app/?

**Comment by sunetraalex** [comment]
Yes, it is working properly now!

Thank you for fixing it so quickly! 🙋

![Screenshot_2023-02-12-07-24-45-421_com android chrome](https://user-images.githubusercontent.com/17137223/218296483-43fe74d9-dc86-47d5-b887-90489c3b5555.jpg)
